apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-configs
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: demo-app
    repoURL: https://github.com/maxim-edb/demo-app-ocp.git
    targetRevision: dev
